# ==========================================
# 1. NOME DA APLICAÇÃO E PORTA (RAILWAY)
# ==========================================
spring.application.name=api
server.port=${PORT:8080}

# ==========================================
# 2. CONEXÃO COM O BANCO DE DADOS (SUPABASE)
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Permite que o Spring crie/atualize as tabelas automaticamente no Supabase
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
api.version=/api/v1

# ==========================================
# 3. SEGURANÇA (CHAVE SECRETA DO SUPABASE)
# ==========================================
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SUPABASE_JWK_SET_URI}
logging.level.org.springframework.security=TRACE
